.github/actions/generate-dependencies-notice/action.yml
.github/actions/generate-dependencies-notice/index.js
.github/actions/generate-dependencies-notice/package-lock.json
.github/actions/generate-dependencies-notice/package.json
.github/workflows/build-snapshot.yml
.github/workflows/gitleaks.yml
.github/workflows/helm-release.yml
.github/workflows/kics.yml
.github/workflows/release.yml
.github/workflows/trivy.yml

* add github actions for tag version
* add github actions for security checks

add github actions for release and security

---

.github/workflows/trivy.yml
backend/src/main/resources/static/discovery-finder-openapi.yaml

* Adjust yml to build docker images correct
* Adjust openapi yml with maxItem for array endpoint

Fix trivy and kics scan

---

backend/pom.xml
pom.xml

* increase snakeyaml version to 2.0
* update springboot to 3.0.5
* exclude h2 to only use for local develop

Fix Trivy CVEs

---

CHANGELOG.md
charts/discoveryfinder/Chart.yaml

prepare helm version 0.1.3

---

.github/workflows/veracode-scan.yml

Add veracode scan for discovery-finder in eclipse-tractusx

Veracode scan for discovery-finder in eclipse-tractusx

---

DEPENDENCIES

Update DEPENDENCIES file

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Fix CVE-2023-34035 (update springboot to version 3.1.2)

fix: CVE-2023-34035

---

charts/discoveryfinder/Chart.yaml

Prepare helm release 0.1.5 and image 0.2.2-M1

feat: Prepare helm release 0.1.5 and image 0.2.2-M1

---

backend/src/main/resources/static/discovery-finder-openapi.yaml

Resolved KICS violation in open api yaml file

feat:Resolved KICS violation

---

backend/src/main/resources/static/discovery-finder-openapi.yaml

Resolved KICS violation in open api yaml file.

fix:Feature/kics fix1

---

backend/src/main/resources/static/discovery-finder-openapi.yaml

Resolved KICS violation in open api yaml file.

fix:Resolved KICS violation

---

backend/src/main/resources/static/discovery-finder-openapi.yaml

Fix kics high finding

---

CHANGELOG.md

Add new changelog entry: legal information fot distributions in jar

Add new changelog entry: legal information fot distributions in jar

---

charts/discoveryfinder/Chart.yaml

Prepare release 0.1.6 and image 0.2.3-M1

Prepare release 0.1.6 and image 0.2.3-M1

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/values.yaml

The resource management settings in values.yaml has been adjusted.

Resource management settings adjusted

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/values.yaml

Set limit of cpu to different values in for request and limit to so node can use the resources better.

different values for cpu for request and limit

---

.github/workflows/helm-test.yml
charts/chart-testing-config.yaml
charts/discoveryfinder/Chart.yaml

helm test cases improved. 
1) Build Image step is removed, which was not used during test.
2) Added node_image variable
3) added license to chart-testing-config.yaml

Bug: Improved helm-test

---

CHANGELOG.md

new changelog entries for upcoming version 0.2.4-M1

add new changelog entries for upcoming version 0.2.4-M1

---

charts/discoveryfinder/Chart.yaml

Prepare release 0.1.10 and image 0.2.4-M1

Prepare release 0.1.10 and image 0.2.4-M1

---

.github/workflows/trivy.yml

Changed image ref for Trivy scan

Feat: Changed image ref for trivy scan

---

charts/discoveryfinder/Chart.yaml

Incremented  'versions' and 'appVersion' in Chart.yaml

Prepare helm release 0.1.12 and image 0.2.5

---

.github/actions/generate-dependencies-notice/action.yml
.github/actions/generate-dependencies-notice/index.js
.github/workflows/build-snapshot.yml
.github/workflows/gitleaks.yml
.github/workflows/helm-release.yml
.github/workflows/helm-test.yml
.github/workflows/kics.yml
.github/workflows/publish-image-discovery-finder.yml
.github/workflows/release.yml
.github/workflows/trivy.yml
.github/workflows/veracode.yaml
backend/src/test/java/org/eclipse/tractusx/discoveryfinder/ApplicationReadyEventListenerTest.java

Legal information header has been corrected:
- the legal information header will start at line 1 in each class
- double copyright expression like "Copyright (c) 2023 Copyright (c) 2023" have been corrected

Legal information header corrected

---

.github/workflows/discoveryfinder-e2e-test.yml
e2e-tests/discoveryfinder/common.yaml
e2e-tests/discoveryfinder/stage_auth.yaml
e2e-tests/discoveryfinder/test_api.tavern.yaml
e2e-tests/requirements.txt

include e2e Tests for discoveryfinder

include e2e Tests for discoveryfinder

---

CHANGELOG.md

Cleaned changelog.md. removed unnecessary version.

Bug: Clean CHANGELOG.md

---

README.md

README.md updated to avoid 404 error.
fixes #69

update README.md to avoid 404 at DockerHub

---

SECURITY.md

Updates SECURITY.md to newer version.
fixes #70

update SECURITY.md to newer version

---

.github/workflows/trivy.yml

fixes to prevent trivy scan failure caused by found high findings.

fixes for trivy scan failure

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/values.yaml

Remove ingress annotation from default values.

remove ingress annotation

---

CHANGELOG.md
DEPENDENCIES
pom.xml

fixes found findings forCVE-2023-34053, CVE-2023-46589 and CVE-2023-6378

fixes findings for CVE-2023-34053, CVE-2023-46589 and CVE-2023-6378

---

charts/discoveryfinder/Chart.yaml

Update helm release to 0.1.14 /image to 0.2.6

Update helm release to 0.1.14 /image to 0.2.6

---

CHANGELOG.md
backend/src/main/java/org/eclipse/tractusx/discoveryfinder/ApiExceptionHandler.java
backend/src/main/java/org/eclipse/tractusx/discoveryfinder/DiscoveryFinderProperties.java
backend/src/main/java/org/eclipse/tractusx/discoveryfinder/model/Endpoint.java
backend/src/main/resources/application-local.yml
backend/src/main/resources/db/changelog/db.changelog-v1.yaml
backend/src/main/resources/static/discovery-finder-openapi.yaml
backend/src/test/java/org/eclipse/tractusx/discoveryfinder/AbstractDiscoveryFinderApi.java
backend/src/test/java/org/eclipse/tractusx/discoveryfinder/DiscoveryFinderApiDelegateTest.java
backend/src/test/java/org/eclipse/tractusx/discoveryfinder/DiscoveryFinderApiSecurityTest.java
backend/src/test/java/org/eclipse/tractusx/discoveryfinder/mapper/DiscoveryFinderMapperTest.java
backend/src/test/resources/application-onstartuptest.yml
charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/values.yaml
docs/6-concepts.md
e2e-tests/discoveryfinder/test_api.tavern.yaml

new field for Endpoint introduced. Now the endpoint also returns a timeToLive value.

Introduce new timeToLive field

---

charts/discoveryfinder/Chart.yaml

Release helm version 0.1.16 with image 0.2.7

feat;Release helm version 0.1.16 with image 0.2.7

---

.github/ISSUE_TEMPLATE/sldt-story.md

Add Issue template in .Github

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/values.yaml

Change existingSecret Name

---

.github/ISSUE_TEMPLATE/sldt-story.md
.github/dependabot.yml

Add dependabot

---

.github/workflows/hotfix-release.yml

Introduce github action for release with selected branch

Introduce github action for release with selected branch

---

charts/discoveryfinder/Chart.yaml

Update postgresql to 12.12.10

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md
charts/discoveryfinder/templates/_helpers.tpl
charts/discoveryfinder/templates/deployment.yaml
charts/discoveryfinder/templates/ingress.yaml
charts/discoveryfinder/templates/postgres-init.yaml
charts/discoveryfinder/templates/secret.yaml
charts/discoveryfinder/templates/service.yaml
charts/discoveryfinder/values.yaml

Helm Improvements:
-More flexibility to configure helm

Helm Improvements

---

DEPENDENCIES
pom.xml

Update springboot to version 3.2.2

Update springboot to version 3.2.2

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/templates/_helpers.tpl
charts/discoveryfinder/templates/postgres-init.yaml

Postgres variable configurable

Postgres variable configurable

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/templates/deployment.yaml
charts/discoveryfinder/values.yaml

remove hard coded password from values.yml

remove hard coded password from values.yml

---

.github/workflows/publish-image-discovery-finder.yml
DOCKER_NOTICE.md
README.md

separate docker notice file

---

backend/src/main/resources/db/changelog/db.changelog-extensions.yaml
backend/src/main/resources/static/discovery-finder-openapi.yaml
pom.xml

corrected copyright headers years range

corrected copyright headers years range

---

charts/discoveryfinder/Chart.yaml

Helm version 0.2.4-RC1

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Update Springboot to version 3.2.4

Update Springboot to version 3.2.4

---

CHANGELOG.md

Prepare stabil version 0.3.0

---

charts/discoveryfinder/Chart.yaml

Prepare helm release 0.2.4

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Security fix for spring-web:6.1.5.jar

Fix:Security fix for spring-web:6.1.5.jar

---

charts/discoveryfinder/Chart.yaml

Helm release 0.2.5
App version 0.3.1

Feat:Helm release 0.2.5

---

.github/workflows/publish-image-discovery-finder.yml
backend/Dockerfile

Fixing pipeline issue after mandatory license addition

Fix: Fixing pipeline issue after mandatory license addition

---

.github/workflows/trivy.yml

Adjust trivy scan

---

DEPENDENCIES
backend/src/main/resources/application.yml
pom.xml

Fix: High Security fix

---

.github/workflows/trivy.yml

fix yml file

---

CHANGELOG.md

Prep: Prepare release 0.4.0

---

charts/discoveryfinder/Chart.yaml

Prep: Prepare helm release 0.3.0

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md
charts/discoveryfinder/templates/deployment.yaml

Add trg 0-4-7 readonly file

---

.tractusx

TRG-1.08. Added swagger path to .tractusx file

Fix: Added swagger path to .tractusx file

---

.github/workflows/trivy.yml
.trivyignore

Added .trivyignore file to mitigate resolved trivy security issue

Fix: Added .trivyignore file

---

CHANGELOG.md
pom.xml

Fix security Issues

---

CHANGELOG.md
pom.xml

Delete old springframework version 6.1.6

Delete old version springframework version 6.1.6

---

CHANGELOG.md
DEPENDENCIES
pom.xml

prepare release 0.5.0

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md

Prepare helm release 0.4.0

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Update springboot to 3.3.5

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md

prepare helm release 0.4.1

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md

Prepare helm release 0.4.2

---

CHANGELOG.md
DEPENDENCIES
pom.xml

Fixed CVE security issue tomcat embedded

Fix: CVE security issue tomcat embedded

---

charts/discoveryfinder/Chart.yaml
charts/discoveryfinder/README.md

Prepare Helm release version 0.5.0

Prepare Helm release version 0.5.0
